Homework/23_10
TheSteinHaus/fefu-ios-base-repo pull request #2
Opened 2021-10-29 13:02 UTC by TheSteinHaus

2021-11-01 09:56 UTC, fplsv requested changes

2021-11-01 09:56 UTC, fplsv commented on fefuactivity/ListlViewController.swift
я отвечу сюда, чтобы гит пометил это как ревью изменений
------
Цвет чутка не по дизу
<img width="250" alt="image" src="https://user-images.githubusercontent.com/49048605/139653544-4e4bc400-1eb0-492a-a3c8-944a974aff16.png">


-------

дата сурс конеш есть, но хотелось бы видеть, как ты с данными работаешь, а не с цифрами и выводом.

ну, что-то в духе

```swift
numberOfRows {
   return data.count
}
```

```swift
cellForRow {
   let cell = ...
   cell.distanceLabel.text = "12345 km"
   ...
}
```

------

нету перехода на экран просмотра. бегло глянул по коду - ты закоментировал segue

------

пока оценка 6, доделаешь - повысим

2021-11-04 05:00 UTC, TheSteinHaus commented
Доделал 1 и 2 дз

2021-11-21 13:56 UTC, fplsv commented
Оценка - 5 по верхнему пределу, ибо не в срок получилось. Давай быстренько делай другое задание. Если в конце дисциплины будет че-то не хватать или сам захочешь оценку выше - решим вопрос.

2021-11-21 13:56 UTC, merged

2021-11-21 13:57 UTC, fplsv commented
> Оценка - 5 по верхнему пределу, ибо не в срок получилось. Давай быстренько делай другое задание. Если в конце дисциплины будет че-то не хватать или сам захочешь оценку выше - решим вопрос.

Обманул кстати. Ставлю пока 8, но все остальное будет в силе