Homework/23_11
TheSteinHaus/fefu-ios-base-repo pull request #4
Opened 2021-12-03 08:30 UTC by TheSteinHaus

2021-12-06 01:41 UTC, fplsv commented
Начнем с того, что оценка 10, молодец, ща дальше ревью кину

2021-12-06 01:46 UTC, fplsv requested changes

2021-12-06 01:46 UTC, fplsv commented on cells/CollectionViewCell.swift
> +                self.layer.borderColor = UIColor.lightGray.cgColor
для таких вещей можно использовать тернарный оператор

```swift
layer.borderWidth = isSelected ? 2 : 1
layer.borderColor = isSelected ? UIColor.purple.cgColor : UIColor.lightGray.cgColor
```

2021-12-06 01:46 UTC, fplsv commented on fefuactivity/MapViewController.swift
> +var start : CLLocation?
вот эти переменные можно и в класс засунуть

2021-12-06 01:46 UTC, fplsv commented on fefuactivity/MapViewController.swift
> +    let motivationWords = ["Только вперёд!", "На Олимп!", "Не сдаваться!", "Топление к мечте!", "Наваливание!"]
хех

2021-12-08 04:42 UTC, fplsv commented
@TheSteinHaus

2021-12-08 07:30 UTC, TheSteinHaus commented
@fplsv Не успел сделать вывод активности, до выходных постараюсь доделать

Остальные штуки в ближайшее время поправлю

2021-12-18 03:42 UTC, fplsv commented
Нуууууууууу ладно поставлю

2021-12-18 03:42 UTC, merged